// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:fast_flow/features/fasting/domain/entities/fasting_record.dart';
import 'package:fast_flow/features/fasting/domain/entities/fasting_schedule.dart';
import 'package:fast_flow/features/onboarding/domain/entities/user_profile.dart';
import 'package:fast_flow/features/weight/domain/entities/weight_entry.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(DailyScheduleAdapter());
    registerAdapter(FastingRecordAdapter());
    registerAdapter(FastingScheduleAdapter());
    registerAdapter(UserProfileAdapter());
    registerAdapter(WeightEntryAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(DailyScheduleAdapter());
    registerAdapter(FastingRecordAdapter());
    registerAdapter(FastingScheduleAdapter());
    registerAdapter(UserProfileAdapter());
    registerAdapter(WeightEntryAdapter());
  }
}
